// <auto-generated />
using System;
using RequestFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RequestFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SupportRequestsDbContext))]
    partial class SupportRequestsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestFlow.Domain.SupportRequests.SupportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Requester")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Requester")
                        .HasDatabaseName("IX_SupportRequests_Requester");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_SupportRequests_Title");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc")
                        .HasDatabaseName("IX_SupportRequests_Status_Priority_CreatedAtUtc");

                    b.ToTable("SupportRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupportRequests_CompletedAtUtc", "([Status] = 'Completed' AND [CompletedAtUtc] IS NOT NULL) OR ([Status] <> 'Completed' AND [CompletedAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_SupportRequests_Priority", "[Priority] IN ('Low', 'Medium', 'High')");

                            t.HasCheckConstraint("CK_SupportRequests_Status", "[Status] IN ('Open', 'InProgress', 'Completed')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
